### ISSUE TITLE
Incorrect syntax in README.md

### ISSUE THREAD

**Issue by ruv** [Candid-Moe/Zorth#1]
## Links

Some links in markdown are incorrect:
https://github.com/Candid-Moe/Zorth/blob/d4f0a3677e6c55eaec8f1dda7fba5b1f4de47cdd/README.md?plain=1#L8

A leading exclamation mark «`!`» means that the link is for an image (see [docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images)).  Since the links to "Forth Standard" and "gForth" are not to images, they do not work.

Correct code for these links:
```markdown
[Forth Standard](https://forth-standard.org/standard/core)
[gForth](https://gforth.org/)
```

## Stack diagrams
Some stack diagrams are confusing:
https://github.com/Candid-Moe/Zorth/blob/d4f0a3677e6c55eaec8f1dda7fba5b1f4de47cdd/README.md?plain=1#L63-L65

In the [stack notation](https://forth-standard.org/standard/notation#subsection.2.2.2), a stack id is followed by a colon «`:`» (not vice versa).  A semicolon is sometimes used to separate stacks in a single diagram.

Less confusing diagrams:
```markdown
**>cs** ( x -- ; C: -- x ) Push TOS to the control stack
**cs>** ( -- x ; C: x -- ) Pops _x_ from control stack and pushes it into the data stack.
```

**Comment by Candid-Moe** [comment]
Corrected. Thanks for your attention.
